#############
#  MIT KDC  #
#############

mitkdc: no
krb5_realm: CLOUDERA.COM
krb5_kdc_type: MIT KDC
krb5_kdc_host: "{{ hostvars[groups.krb5_server[0]].private_hostname }}"
krb5_kdc_admin_user: "cloudera-scm/admin@{{ krb5_realm }}"
krb5_kdc_admin_passwd: Cloudera20!!
krb5_kdc_master_passwd: Cloudera20!!
krb5_enc_types: aes256-cts aes128-cts rc4-hmac

###########
#  RDBMS  #
###########
db:
  type: MariaDB 
  version: '10.1'
  root_password: cloudera
  configFiles:
    mycnf: |
      [mysqld]
      datadir=/var/lib/mysql
      socket=/var/lib/mysql/mysql.sock
      transaction-isolation = READ-COMMITTED
      symbolic-links = 0
      key_buffer = 16M
      key_buffer_size = 32M
      max_allowed_packet = 32M
      thread_stack = 256K
      thread_cache_size = 64
      query_cache_limit = 8M
      query_cache_size = 64M
      query_cache_type = 1

      max_connections = 550
      server_id=1
      binlog_format = mixed

      read_buffer_size = 2M
      read_rnd_buffer_size = 16M
      sort_buffer_size = 8M
      join_buffer_size = 8M

      # InnoDB settings
      innodb_file_per_table = 1
      innodb_flush_log_at_trx_commit  = 2
      innodb_log_buffer_size = 64M
      innodb_buffer_pool_size = 4G
      innodb_thread_concurrency = 8
      innodb_flush_method = O_DIRECT
      innodb_log_file_size = 512M

      [mysqld_safe]
      log-error=/var/log/mariadb/mariadb.log
      pid-file=/var/run/mariadb/mariadb.pid

      #
      # include all files from the config directory
      #
      !includedir /etc/my.cnf.d


##################
# INFRASTRUCTURE #
##################
instances:
  user: centos

  region: RegionOne
  security_group: 
    - default
  public_key_id: "{{ public_key }}" 

  # Variables for the new Fusion Cloud
  cloud: openstack
  interface: public
  az: "{{ az }}"
  subnet: "{{ subnet }}" #SE-GOES_INTERNAL_NET
  image: "CentOS 7"
  auto_ip: no
  domain: "{{ domain }}" #se-goes.fuse.l42.cloudera.com 
  bootstrap: |
    #!/bin/bash
    hostnamectl set-hostname $(echo "`hostname | cut -d"." -f1`.{{ domain }}")

  # Variables for the old Field Cloud
  # cloud: field
  # interface: internal
  # az: SE
  # auto_ip: yes
  # subnet: "PROVIDER_NET_172.26.192.0/18"
  # image: "CentOS 7.4"
  # domain: field.hortonworks.com


  tags:
    owner: "{{ owner }}"
    enddate: "{{ end_date }}"
    project: " {{ project_name }}"

  instance_groups:  
    - inventory_group: 
        - main_master
        - masters
        - db_server 
        - cm_server
        - cdf
        - efm
        - minifi
        - cdsw_master
        - cdpdc
      exact_count: 1
      instance_type: "{{ instance_type | default('m1.xlarge.ram') }}"
      bootstrap: |
        #!/bin/bash
        
        # uncomment below if you are on Fusion Cloud
        hostnamectl set-hostname $(echo "`hostname | cut -d"." -f1`.{{ domain }}")

        dd if=/dev/zero of=/root/diskimage bs=1M count=51200 
        echo "finished dd" > /root/loop.txt
        mkfs.ext4 -F /root/diskimage 
        echo "finished mkfs" >> /root/loop.txt
        losetup -d /dev/loop0
        sleep 20
        losetup /dev/loop0 /root/diskimage
        echo "finished losetup" >> /root/loop.txt 
        
      tags:
        Name: "{{ deployment_id }}-SNC"   # mandatory tag
        deployment_id: "{{ deployment_id }}"
